### ISSUE TITLE
Normalize OSIO env vars naming

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-backend#365]
I would suggest renaming to `LAUNCHER_OSIO_...` for:
- `WIT_URL`: `LAUNCHER_OSIO_WIT_URL`
- `AUTH_URL`: `LAUNCHER_OSIO_AUTH_URL`
- `OPENSHIFT_API_URL`: `LAUNCHER_OSIO_OPENSHIFT_API_URL`
- `JENKINS_URL`: `LAUNCHER_OSIO_JENKINS_URL`

remove `KEYCLOAK_SAAS_URL`
remove from template.yaml
```
- name: KEYCLOAK_SAAS_URL
            valueFrom:
              configMapKeyRef:
                name: launcher
                key: osio.keycloak.saas.url
```
